version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./coda-utilities/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb"
      MYSQL_DATABASE: "mariadb"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "mariadb"
    restart: always
  coda-utilites:
    build: .
    volumes:
      - ./env.js:/app/env.js
    depends_on:
      - db
    restart: always
