name: eslint
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
    - name: Install eslint
      run: npm install -g eslint@8.57.0
    - name: Run eslint
      run: eslint --ext .js .
