name: eslint
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0
    - name: Install eslint
      run: npm install -g eslint
    - name: Run eslint
      run: eslint --ext .js .